'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On


Namespace My
    
    <Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0"),  _
     Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
    Partial Friend NotInheritable Class MySettings
        Inherits Global.System.Configuration.ApplicationSettingsBase
        
        Private Shared defaultInstance As MySettings = CType(Global.System.Configuration.ApplicationSettingsBase.Synchronized(New MySettings()),MySettings)
        
#Region "My.Settings Auto-Save Functionality"
#If _MyType = "WindowsForms" Then
    Private Shared addedHandler As Boolean

    Private Shared addedHandlerLockObject As New Object

    <Global.System.Diagnostics.DebuggerNonUserCodeAttribute(), Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)> _
    Private Shared Sub AutoSaveSettings(ByVal sender As Global.System.Object, ByVal e As Global.System.EventArgs)
        If My.Application.SaveMySettingsOnExit Then
            My.Settings.Save()
        End If
    End Sub
#End If
#End Region
        
        Public Shared ReadOnly Property [Default]() As MySettings
            Get
                
#If _MyType = "WindowsForms" Then
               If Not addedHandler Then
                    SyncLock addedHandlerLockObject
                        If Not addedHandler Then
                            AddHandler My.Application.Shutdown, AddressOf AutoSaveSettings
                            addedHandler = True
                        End If
                    End SyncLock
                End If
#End If
                Return defaultInstance
            End Get
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("a275b802aa1aadfd492bf2ae66a9c040")>  _
        Public Property Shopify_API_Key() As String
            Get
                Return CType(Me("Shopify_API_Key"),String)
            End Get
            Set
                Me("Shopify_API_Key") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("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")>  _
        Public Property Shopify_Secret_Key() As String
            Get
                Return CType(Me("Shopify_Secret_Key"),String)
            End Get
            Set
                Me("Shopify_Secret_Key") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://msread.myshopify.com/")>  _
        Public Property Shopify_Store_URL() As String
            Get
                Return CType(Me("Shopify_Store_URL"),String)
            End Get
            Set
                Me("Shopify_Store_URL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("http://www.teamjello.com/")>  _
        Public Property Shopify_App_URL() As String
            Get
                Return CType(Me("Shopify_App_URL"),String)
            End Get
            Set
                Me("Shopify_App_URL") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Data Source=wannatalkghl.cys7xzxa94iq.ap-southeast-1.rds.amazonaws.com,1433;Initi"& _ 
            "al Catalog=lechurntest;Persist Security Info=False;User ID=admin;Password=Sophie"& _ 
            "383838")>  _
        Public Property Shopify_App_DB_Conn() As String
            Get
                Return CType(Me("Shopify_App_DB_Conn"),String)
            End Get
            Set
                Me("Shopify_App_DB_Conn") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("X-Shopify-Shop-Api-Call-Limit")>  _
        Public Property Shopify_API_Rate_Limit_Header() As String
            Get
                Return CType(Me("Shopify_API_Rate_Limit_Header"),String)
            End Get
            Set
                Me("Shopify_API_Rate_Limit_Header") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("Retry-After")>  _
        Public Property Shopify_API_Rate_Limit_Retry_Header() As String
            Get
                Return CType(Me("Shopify_API_Rate_Limit_Retry_Header"),String)
            End Get
            Set
                Me("Shopify_API_Rate_Limit_Retry_Header") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("40/40")>  _
        Public Property Shopify_API_Call_Limit() As String
            Get
                Return CType(Me("Shopify_API_Call_Limit"),String)
            End Get
            Set
                Me("Shopify_API_Call_Limit") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("3288974491757")>  _
        Public Property Shopify_API_Dummy_CustomerID() As String
            Get
                Return CType(Me("Shopify_API_Dummy_CustomerID"),String)
            End Get
            Set
                Me("Shopify_API_Dummy_CustomerID") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("92eb4c96c2882b6f2dacf25073d56a07")>  _
        Public Property Shopify_API_Key_Public_() As String
            Get
                Return CType(Me("Shopify_API_Key_Public_"),String)
            End Get
            Set
                Me("Shopify_API_Key_Public_") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("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")>  _
        Public Property Shopify_Secret_Key_Public() As String
            Get
                Return CType(Me("Shopify_Secret_Key_Public"),String)
            End Get
            Set
                Me("Shopify_Secret_Key_Public") = value
            End Set
        End Property
        
        <Global.System.Configuration.UserScopedSettingAttribute(),  _
         Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
         Global.System.Configuration.DefaultSettingValueAttribute("https://test-store-113344432.myshopify.com/")>  _
        Public Property Shopify_Store_URL_Public() As String
            Get
                Return CType(Me("Shopify_Store_URL_Public"),String)
            End Get
            Set
                Me("Shopify_Store_URL_Public") = value
            End Set
        End Property
    End Class
End Namespace

Namespace My
    
    <Global.Microsoft.VisualBasic.HideModuleNameAttribute(),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute()>  _
    Friend Module MySettingsProperty
        
        <Global.System.ComponentModel.Design.HelpKeywordAttribute("My.Settings")>  _
        Friend ReadOnly Property Settings() As Global.ShopifyLibrary.My.MySettings
            Get
                Return Global.ShopifyLibrary.My.MySettings.Default
            End Get
        End Property
    End Module
End Namespace
